### ISSUE TITLE
Cannot compile on linux

### ISSUE THREAD

**Issue by frostyplanet** [asomers/mio-aio#13]
ubuntu 18.04

Cargo.tml
```
[dependencies]
rand = "0.7.0"
mio-aio = "0.4.1"
mio = "0.6.13"
```

```
$ rustc --version
rustc 1.38.0-nightly (60960a260 2019-08-12)
```

I have not written any code yet,  cargo build has the following error

> 
> cargo build
>    Compiling mio-aio v0.4.1
> error: no variant `SigevKevent` in enum `nix::sys::signal::SigevNotify`
>    --> /home/plan/.cargo/registry/src/mirrors.ustc.edu.cn-27933024a10d4e91/mio-aio-0.4.1/src/aio.rs:199:34
>     |
> 199 |         let sigev = SigevNotify::SigevKevent{kq, udata: udata as isize};
>     |                                  ^^^^^^^^^^^ variant not found in `nix::sys::signal::SigevNotify`
> 
> error[E0599]: no method named `is_lio` found for type `mio::unix::UnixReady` in the current scope
>    --> /home/plan/.cargo/registry/src/mirrors.ustc.edu.cn-27933024a10d4e91/mio-aio-0.4.1/src/aio.rs:375:41
>     |
> 375 |         assert!(UnixReady::from(events).is_lio());
>     |                                         ^^^^^^ help: there is a method with a similar name: `is_aio`
> 
> error: no variant `SigevKevent` in enum `nix::sys::signal::SigevNotify`
>    --> /home/plan/.cargo/registry/src/mirrors.ustc.edu.cn-27933024a10d4e91/mio-aio-0.4.1/src/aio.rs:378:34
>     |
> 378 |         let sigev = SigevNotify::SigevKevent{kq, udata: udata as isize};
>     |                                  ^^^^^^^^^^^ variant not found in `nix::sys::signal::SigevNotify`
> 
> error: aborting due to 3 previous errors
> 
> For more information about this error, try `rustc --explain E0599`.
> error: Could not compile `mio-aio`.

**Comment by frostyplanet** [comment]
sorry, did not read about not supporting linux,  in thoery doable using system call

**Comment by asomers** [comment]
Right, mio-aio will never run on Linux, unless Linux gets serious about implementing POSIX AIO.  Linux's libaio is an alternative, but the API is fairly different.  It's also super-inconvenient; it doesn't work on every file system, doesn't support fsync and IIRC requires buffers to be multiples of 512 bytes in size.  A newer alternative is IO-uring.  That might work better than libaio, but the API is even more different.  In either case, it would require a separate crate.  mio-aio will stick with POSIX AIO only.
