### ISSUE TITLE
libaio can deliver completion with eventfd

### ISSUE THREAD

**Issue by da-x** [asomers/mio-aio#3]
In the README you mention that in Linux, `libaio` cannot deliver notification via `epoll`, and the only alternative is via signal delivery. That has been only true until 2007, when a change in the kernel ([signal/timer/event: KAIO eventfd support example · torvalds/linux@9c3060b](https://github.com/torvalds/linux/commit/9c3060bedd84144653a2ad7bea32389f65598d40)) introduced `eventfd` support. It is actively used by many these days, as it integrated nicely with `epoll`. See the `io_set_eventfd` API of `libaio`.

**Comment by asomers** [comment]
Thanks for the tip, @da-x .  However, I can't find any documentation for `io_set_eventfd`; just a few Stack Exchange posts.  Is there a man page for that function anywhere?  Do you know of any examples that use it?

**Comment by da-x** [comment]
A man page for this function is indeed [missing](https://www.kernel.org/doc/man-pages/missing_pages.html) from the `man-pages` package. Is [this](http://adolgarev.blogspot.co.il/2013/12/aio-with-epoll-event-loop.html) good enough? I can validate it from knowing this API.
